import { PROJECTS_DATA } from './projects';
export { PROJECTS_DATA };

// Dynamic Media Imports
const videoModules = import.meta.glob('./assets/videos/**/*.{mp4,webm,mov}', { eager: true, query: '?url', import: 'default' });
const audioModules = import.meta.glob('./assets/audio/*.{mp3,wav,ogg}', { eager: true, query: '?url', import: 'default' });

const VIDEO_URLS = Object.values(videoModules) as string[];
const AUDIO_URLS = Object.values(audioModules) as string[];

// Lightweight thumbnail (public/thumbs/, generated by generate_thumbs.sh).
// Same filename as the original; used for hover previews and the index view.
export const getThumbUrl = (filename?: string): string =>
  filename ? `/thumbs/${filename}` : '';

export const getMediaUrl = (mediaType: 'image' | 'video' | 'audio', index: number, filename?: string): string => {
  if (filename) {
    if (mediaType === 'image') {
      return `/images/${filename}`;
    } else if (mediaType === 'video') {
      // If it's an external URL, return it directly
      if (filename.startsWith('http')) {
        return filename;
      }
      // Find the module that ends with the filename or contains the basename (for hashed files)
      const basename = filename.substring(0, filename.lastIndexOf('.'));
      const found = VIDEO_URLS.find(url => url.includes(filename) || (basename && url.includes(basename)));
      return found || '';
    } else if (mediaType === 'audio') {
      const basename = filename.substring(0, filename.lastIndexOf('.'));
      const found = AUDIO_URLS.find(url => url.includes(filename) || (basename && url.includes(basename)));
      return found || '';
    }
  }

  // Fallback to index-based assignment if no filename provided
  if (mediaType === 'video') {
    if (VIDEO_URLS.length > 0) {
      return VIDEO_URLS[index % VIDEO_URLS.length];
    }
    return '';
  } else if (mediaType === 'audio') {
    if (AUDIO_URLS.length > 0) {
      return AUDIO_URLS[index % AUDIO_URLS.length];
    }
    return '';
  } else {
    return `/images/image${String(index + 1).padStart(5, '0')}.jpg`;
  }
};
