import { Project } from './types';

export const PROJECTS_DATA: Omit<Project, 'id' | 'imageUrl'>[] = [
    // Images
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00001.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00002.jpg' },
    { title: "", client: "", year: "2016", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00003.jpg' },
    { title: "", client: "", year: "2019", type: "den haag, netherlands", description: "", mediaType: 'image', src: 'image00004.jpg' },
    { title: "", client: "", year: "2019", type: "frankfurt, germany", description: "", mediaType: 'image', src: 'image00005.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00006.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00007.jpg' },
    { title: "", client: "", year: "2019", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00008.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00009.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00010.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00011.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00012.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00013.jpg' },
    { title: "", client: "", year: "2019", type: "paris, france", description: "", mediaType: 'image', src: 'image00014.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00015.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00016.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00017.jpg' },
    { title: "", client: "", year: "2019", type: "den haag, netherlands", description: "", mediaType: 'image', src: 'image00018.jpg' },
    { title: "", client: "", year: "2019", type: "paris, france", description: "", mediaType: 'image', src: 'image00019.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00020.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00021.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00022.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00023.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00024.jpg' },
    { title: "", client: "", year: "2018", type: "namyangju, south korea", description: "", mediaType: 'image', src: 'image00025.jpg' },
    { title: "", client: "", year: "2019", type: "den haag, netherlands", description: "", mediaType: 'image', src: 'image00026.jpg' },
    { title: "", client: "", year: "2019", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00027.jpg' },
    { title: "", client: "", year: "2019", type: "den haag, netherlands", description: "", mediaType: 'image', src: 'image00028.jpg' },
    { title: "", client: "", year: "2019", type: "amsterdam, netherlands", description: "", mediaType: 'image', src: 'image00029.jpg' },
    { title: "", client: "", year: "2019", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00030.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00031.jpg' },
    { title: "", client: "", year: "2019", type: "paris, france", description: "", mediaType: 'image', src: 'image00032.jpg' },
    { title: "", client: "", year: "2019", type: "assevillers, france", description: "", mediaType: 'image', src: 'image00033.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00034.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00035.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00036.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00037.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00038.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00039.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00040.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00041.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00042.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00043.jpg' },
    { title: "", client: "", year: "2020", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00044.jpg' },
    { title: "", client: "", year: "2020", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00045.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00046.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00047.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00048.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00049.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00050.jpg' },
    { title: "", client: "", year: "2019", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00051.jpg' },
    { title: "", client: "", year: "2019", type: "möckern, germany", description: "", mediaType: 'image', src: 'image00052.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00053.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00054.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00055.jpg' },
    { title: "", client: "", year: "2019", type: "hoogland, netherlands", description: "", mediaType: 'image', src: 'image00056.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00057.jpg' },
    { title: "", client: "", year: "2020", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00058.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00059.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00060.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00061.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00062.jpg' },
    { title: "", client: "", year: "2019", type: "paris, france", description: "", mediaType: 'image', src: 'image00063.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00064.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00065.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00066.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00067.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00068.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00069.jpg' },
    { title: "", client: "", year: "2019", type: "paris, france", description: "", mediaType: 'image', src: 'image00070.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00071.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00072.jpg' },
    { title: "", client: "", year: "2019", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00073.jpg' },
    { title: "", client: "", year: "2019", type: "hoogstraten, netherlands", description: "", mediaType: 'image', src: 'image00074.jpg' },
    { title: "", client: "", year: "2017", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00075.jpg' },
    { title: "", client: "", year: "2019", type: "berlin, germany", description: "", mediaType: 'image', src: 'image00076.jpg' },
    { title: "", client: "", year: "2018", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00077.jpg' },
    { title: "", client: "", year: "2019", type: "hoogstraten, netherlands", description: "", mediaType: 'image', src: 'image00078.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00079.jpg' },
    { title: "", client: "", year: "2025", type: "tokyo, japan", description: "", mediaType: 'image', src: 'image00080.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00081.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00082.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00083.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00084.jpg' },
    { title: "", client: "", year: "2022", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00085.jpg' },
    { title: "", client: "", year: "2022", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00086.jpg' },
    { title: "", client: "", year: "2022", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00087.jpg' },
    { title: "", client: "", year: "2022", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00088.jpg' },
    { title: "", client: "", year: "2022", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00089.jpg' },
    { title: "", client: "", year: "2022", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00090.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00091.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00092.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00093.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00094.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00095.jpg' },
    { title: "", client: "", year: "2017", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00096.jpg' },
    { title: "", client: "", year: "2017", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00097.jpg' },
    { title: "", client: "", year: "2025", type: "tokyo, japan", description: "", mediaType: 'image', src: 'image00098.jpg' },
    { title: "", client: "", year: "2025", type: "tokyo, japan", description: "", mediaType: 'image', src: 'image00099.jpg' },
    { title: "", client: "", year: "2025", type: "tokyo, japan", description: "", mediaType: 'image', src: 'image00100.jpg' },
    { title: "", client: "", year: "2025", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00101.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00102.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00103.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00104.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00105.jpg' },
    { title: "", client: "", year: "2019", type: "chungcheong, south korea", description: "", mediaType: 'image', src: 'image00106.jpg' },
    { title: "", client: "", year: "2020", type: "jeju, south korea", description: "", mediaType: 'image', src: 'image00107.jpg' },
    { title: "", client: "", year: "2025", type: "tokyo, japan", description: "", mediaType: 'image', src: 'image00108.jpg' },
    { title: "", client: "", year: "2019", type: "hoogstraten, netherlands", description: "", mediaType: 'image', src: 'image00109.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00110.jpg' },
    { title: "", client: "", year: "2020", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00111.jpg' },
    { title: "", client: "", year: "2020", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00112.jpg' },
    { title: "", client: "", year: "2022", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00113.jpg' },
    { title: "", client: "", year: "2020", type: "seoul, south korea", description: "", mediaType: 'image', src: 'image00114.jpg' },
    { title: "", client: "", year: "2020", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00115.jpg' },
    { title: "", client: "", year: "2020", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00116.jpg' },
    { title: "", client: "", year: "2022", type: "gangwon, south korea", description: "", mediaType: 'image', src: 'image00117.jpg' },



    // Videos (Reduced to match likely file count to avoid duplicates in list view)
    { title: "constant value seoul", client: "#8", year: "2016", type: "seoul, south korea", description: "", mediaType: 'video', src: 'https://gongillee.b-cdn.net/constantvalue8.mp4', previewSrc: 'https://gongillee.b-cdn.net/constantvalue8_preview.mp4' },

    // Audio
    { title: "segment of a circle", client: "scøpe, xanexx, ve bogel", year: "2024", type: "seoul, south korea", description: "Visualizing sound waves in a silent room.", mediaType: 'audio', src: 'segment_of_a_circle.mp3' },
];
